import Foundation

enum Themes {
    static let pool: [String] = [
        "Songs you'd hear at a wedding reception",
        "Songs to cry to at 2am",
        "Songs for a road trip with friends",
        "Songs your mum would love",
        "Songs that feel like summer",
        "Songs for a gym workout",
        "Songs for a villain's entrance",
        "Songs to play at a funeral (respectfully)",
        "Songs that slap at a house party",
        "Songs for falling in love",
        "Songs for a breakup montage",
        "Songs that feel nostalgic for childhood",
        "Songs for a boss battle in a video game",
        "Songs for cooking dinner on a Friday night",
        "Songs for a slow dance",
        "Songs that make you feel invincible",
        "Songs for a movie chase scene",
        "Songs you'd sing drunk at karaoke",
        "Songs for a lazy Sunday morning",
        "Songs that make you want to drive fast",
        "Songs that feel cinematic",
        "Songs for getting ready to go out",
        "Songs for a rainy afternoon indoors",
        "Songs that feel rebellious",
        "Songs to blast at the beach",
        "Songs for meditating or winding down",
        "Songs for a birthday party",
        "Songs for studying or deep focus",
        "Songs for a late night city drive",
        "Songs that feel like the 80s",
        "Songs for dancing alone in your room",
        "Songs that feel dangerous",
        "Songs for a horror movie scene",
        "Songs to play at a BBQ",
        "Songs that feel euphoric",
        "Songs for a sports highlight reel",
        "Songs that make you emotional at the end of a film",
        "Songs for a heist scene",
        "Songs that feel like being young and free",
        "Songs a DJ would play to close out a festival",
        "Songs for a first kiss scene",
        "Songs that feel like Sunday melancholy",
        "Songs to clean the house to",
        "Songs that make a stadium go wild"
    ]
}
